# Generated by Django 3.0.2 on 2020-01-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Season',
            new_name='Seasons',
        ),
    ]
