# Generated by Django 3.0.2 on 2020-01-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_auto_20200126_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodes',
            options={'verbose_name': 'Episodes'},
        ),
        migrations.AlterModelOptions(
            name='seasons',
            options={'verbose_name': 'Seaons'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Series'},
        ),
    ]
