# Generated by Django 3.0.2 on 2020-03-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_auto_20200126_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodes',
            options={'verbose_name_plural': 'Episodes'},
        ),
        migrations.AlterModelOptions(
            name='seasons',
            options={'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='episodes',
            name='image',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
