# Generated by Django 3.0.2 on 2020-03-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_auto_20200308_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='series',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
